{"name": "登录成功", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestLogin' object has no attribute 'data'", "trace": "self = <Testcase.test_one.TestLogin object at 0x000002324EE048E0>\n\n    @allure.title(\"登录成功\")\n    def test_03(self):\n>       user, pwd, hope = self.data[0].values()\nE       AttributeError: 'TestLogin' object has no attribute 'data'\n\nTestcase\\test_one.py:46: AttributeError"}, "start": 1628646183467, "stop": 1628646183468, "uuid": "a9682c31-465a-4dfb-a6fa-0b0671acbc6d", "historyId": "2a65852a0f4f979b6d8db34073a265b6", "testCaseId": "10babd97d345e55d09d5703bef3eb78a", "fullName": "Testcase.test_one.TestLogin#test_03", "labels": [{"name": "feature", "value": "编辑页面"}, {"name": "parentSuite", "value": "Testcase"}, {"name": "suite", "value": "test_one"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "SK-20210625NVCA"}, {"name": "thread", "value": "7132-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Testcase.test_one"}]}